import fs from 'fs'

interface ICleanProps {
  positionEndSlice? : number
  positionStartSlice: number
  text              : string
}

const replacer = (str: string) => ` ${str} `

const cleanGeneralInfo = ({
  text,
  positionStartSlice,
  positionEndSlice
}: ICleanProps): string => {
  if (positionEndSlice)
    text = text.slice(positionStartSlice, positionEndSlice)
  else
    text = text.slice(positionStartSlice)

  return text
    .replace(/:/g, '')
    .replace(/comooptimizar/g, 'cómo optimizar')
    .replace(
      /programación|aspectos|programas|aplicaciones|algoritmos|estructuras|permitan|problemas|objetos|sistemas|digitales|comunicación|estudiantes|datos|básicos|nivel|representaciones|herramienta|como|técnicas|implementar|principios|estudio|métodos|computacional|serán|cualquier|optimización|grandes|áreas|diseño|enfoque|natural|recursos|interconectadas|informáticos|usuario\b|otro|está|fundamentos|profesional|temática|implementación|Computación|servidor|lenguajes|computadoras|tanto|implementan|información|conocer|ensamblador|BIOS|imágenes|dirigir|mejores|análisis|internacionales|sostenibilidad|convolucionales|fundamentales|herramientas|aseguramiento|cotidiana\b|básicas|máquinas|intercambiando/g,
      replacer
    )
    .replace(/temática s/g, 'temáticas')
    .replace(/nivel esde/g, 'niveles de')
    .replace(/nivel esde/g, 'niveles de')
    .replace(/estudiany/g, 'estudian y')
    .replace(/demedio/g, 'de medio')
    .replace(/estrategiasde/g, 'estrategias de')
    .replace(/delsubsistema/g, 'del subsistema')
    .replace(/enla/g, 'en la')
    .replace(/dedispositivo/g, 'de dispositivo')
    .replace(/complementacon/g, 'complementa con')
    .replace(/busese/g, 'buses e')
    .replace(/deeplearning/g, 'deep learning')
    .replace(/dedominios/g, 'de dominios')
    .replace(/quees/g, 'que es')
    .replace(/redesneuronales/g, 'redes neuronales')
    .replace(/partirde/g, 'partir de')
    .replace(/quepuedan/g, 'que puedan')
    .replace(/pararesolver/g, 'para resolver')
    .replace(/dealto/g, 'de alto')
    .replace(/Elaprendizajeprofundo/g, 'El aprendizaje profundo')
    .replace(/laspropiedades/g, 'las propiedades')
    .replace(/nosupervisados/g, 'no supervisados')
    .replace(/elproceso/g, 'el proceso')
    .replace(/talleren/g, 'taller en')
    .replace(/trabajoe/g, 'trabajo e')
    .replace(/larotación/g, 'la rotación')
    .replace(/completarsu/g, 'completar su')
    .replace(/contextocientífico/g, 'contexto científico')
    .replace(/trataránlos/g, 'tratarán los')
    .replace(/laCalidad/g, 'la Calidad')
    .replace(/ofreceuna/g, 'ofrece una')
    .replace(/ymodelamiento/g, 'y modelamiento')
    .replace(/secuenciasde/g, 'secuencias de')
    .replace(/deauditoría/g, 'de auditoría')
    .replace(/continúacon/g, 'continúa con')
    .replace(/posteriormenteen/g, 'posteriormente en')
    .replace(/enfenómenos/g, 'en fenómenos')
    .replace(/secentra/g, 'se centra')
    .replace(/resultadosy/g, 'resultados y')
    .replace(/haráprincipalmente/g, 'hará principalmente')
    .replace(/principalde/g, 'principal de')
    .replace(/ellosse/g, 'ello se')
    .replace(/tecnologías/g, ' tecnologías ')
    .replace(/tecnologías hardware/g, 'tecnologías, hardware')
    .replace(/conel/g, 'con el')
    .replace(/nospermita/g, 'nos permita')
    .replace(/ytomar/g, 'y tomar')
    .replace(/CloudComputing/g, 'Cloud Computing')
    .replace(/hanexperimentado/g, 'han experimentado')
    .replace(/laInteligencia/g, 'la Inteligencia')
    .replace(/entrarmucho/g, 'entrar mucho')
    .replace(/parala/g, 'para la')
    .replace(/porDarwin/g, 'por Darwin')
    .replace(/estoscientíficos/g, 'estos científicos')
    .replace(/mencionarbrevemente/g, 'mencionar brevemente')
    .replace(/”y/g, '” y')
    .replace(/bioinspirados/g, 'bio inspirados')
    .replace(/deenjambres/g, 'de enjambres')
    .replace(/asignaturasde/g, 'asignaturas de')
    .replace(/parael/g, 'para el')
    .replace(/nuevascorrelaciones/g, 'nuevas correlaciones')
    .replace(/dedata/g, 'de data')
    .replace(/incluyendoaquellos/g, 'incluyendo aquellos')
    .replace(/BigData/g, 'Big Data')
    .replace(/ruedasautónomos/g, 'ruedas autónomos')
    .replace(/compuestospor/g, 'compuestos por')
    .replace(/organizacionesindependientes/g, 'organizaciones independientes')
    .replace(/Durantela/g, 'Durante la')
    .replace(/Gridha/g, 'Grid ha')
    .replace(/posiblemuchas/g, 'posible muchas')
    .replace(/tiposde/g, 'tipos de')
    .replace(/deberánpercibir/g, 'deberán percibir')
    .replace(/\)en/g, ') en')
    .replace(/conseguirdebido/g, 'conseguir debido')
    .replace(/laextracción/g, 'la extracción')
    .replace(/conjuntosde/g, 'conjuntos de')
    .replace(/términosde/g, 'términos de')
    .replace(/centrosde/g, 'centros de')
    .replace(/auna/g, 'a una')
    .replace(/novedosoque/g, 'novedoso que')
    .replace(/FogComputing/g, 'Fog Computing')
    .replace(/sensoreso/g, 'sensores o')
    .replace(/balancearlos/g, 'balancear los')
    .replace(/investigadoraen/g, 'investigadora en')
    .replace(/Cienciade/g, 'Ciencia de')
    .replace(/investigacióny/g, 'investigación y')
    .replace(/doctoralesen/g, 'doctorales en')
    .replace(/losinvestigadores/g, 'los investigadores')
    .replace(/entidadesacadémicas/g, 'entidades académicas')
    .replace(/necesidadde/g, 'necesidad de')
    .replace(/escritos\(/g, 'escritos (')
    .replace(/otalleres/g, 'o talleres')
    .replace(/lausabilidad/g, 'la usabilidad')
    .replace(/creaciónde/g, 'creación de')
    .replace(/satisfaganal/g, 'satisfagan al')
    .replace(/profundizaren/g, 'profundizar en')
    .replace(/extensiónfundamental/g, 'extensión fundamental')
    .replace(/alumnodesarrollará/g, 'alumno desarrollará')
    .replace(/losmecanismos/g, 'los mecanismos')
    .replace(/laevaluación/g, 'la evaluación')
    .replace(/previastales/g, 'previas tales')
    .replace(/subdivideen/g, 'subdivide en')
    .replace(/Porun/g, 'Por un')
    .replace(/alos/g, 'a los')
    .replace(/ymultiprocesador/g, 'y multiprocesador')
    .replace(/sincronizacióny/g, 'sincronización y')
    .replace(/comportamientointeligente/g, 'comportamiento inteligente')
    .replace(/tópicosrelacionados/g, 'tópicos relacionados')
    .replace(/complejosen/g, 'complejos en')
    .replace(/agentesinteligentes/g, 'agentes inteligente')
    .replace(/dedecisión/g, 'de decisión')
    .replace(/infraestructuracrítica/g, 'infraestructura crítica')
    .replace(/operacionesdel/g, 'operaciones del')
    .replace(/setrabajarán/g, 'se trabajarán')
    .replace(/tecnologíade/g, 'tecnología de')
    .replace(/tipode/g, 'tipo de')
    .replace(/modernos\(/g, 'modernos (')
    .replace(/eldesarrollo/g, 'el desarrollo')
    .replace(/en2D/g, 'en 2D')
    .replace(/experienciapráctica/g, 'experiencia práctica')
    .replace(/delas/g, 'de las')
    .replace(/laempresa/g, 'la empresa')
    .replace(/operativade/g, 'operativa de')
    .replace(/minimizandoriesgos/g, 'minimizando riesgos')
    .replace(/conocimientosprevios/g, 'conocimientos previos')
    .replace(/seguridadde/g, 'seguridad de')
    .replace(/proporcionarálos/g, 'proporcionará los')
    .replace(/loscampos/g, 'los campos')
    .replace(/suscapacidades/g, 'sus capacidades')
    .replace(/deemprendimiento/g, 'de emprendimiento')
    .replace(/lepondrá/g, 'le pondrá')
    .replace(/productosmultimedia/g, 'productos multimedia')
    .replace(/licenciadotiene/g, 'licenciado tiene')
    .replace(/orientadaa/g, 'orientada a')
    .replace(/problemapermite/g, 'problema permite')
    .replace(/dela/g, 'de la')
    .replace(/adecuadadivisión/g, 'adecuada división')
    .replace(/unamisma/g, 'una misma')
    .replace(/actualesson/g, 'actuales son')
    .replace(/paralelos plataformasde/g, 'paralelos: plataformas de')
    .replace(/dichasarquitecturas/g, 'dichas arquitecturas')
    .replace(/utilicentoda/g, 'utilicen toda')
    .replace(/arquitecturasubyacente/g, 'arquitectura subyacente')
    .replace(/enpocas/g, 'en pocas')
    .replace(/cumplacuatro/g, 'cumpla cuatro')
    .replace(/propiedadesExactitud/g, 'propiedades: Exactitud')
    .replace(/resultadonumérico/g, 'resultado numérico')
    .replace(/escapaz/g, 'es capaz')
    .replace(/problemamatemáticocon/g, 'problema matemático con')
    .replace(/computacionalesrazonables/g, 'computacionales razonables')
    .replace(/entradasx\)/g, 'entradas x)')
    .replace(/precisoes/g, 'preciso es')
    .replace(/imaginartodasesta/g, 'imaginar todas estas')
    .replace(/maneraque/g, 'manera que')
    .replace(/existeuna/g, 'existe una')
    .replace(/pudiendoser/g, 'pudiendo ser')
    .replace(/usuarioscomunicándose/g, 'usuarios comunicándose')
    .replace(/máscosas/g, 'más cosas')
    .replace(/\( ensamblador/g, '(ensamblador')
    .replace(/querequieren/g, 'que requieren')
    .replace(/elHardware/g, 'el Hardware')
    .replace(/deformasegura/g, 'de forma segura')
    .replace(/centralycrítico/g, 'central y crítico')
    .replace(/ciclode/g, 'ciclo de')
    .replace(/losdiferentes/g, 'los diferentes')
    .replace(/lasmétricas/g, 'las métricas')
    .replace(/deidentificar/g, 'de identificar')
    .replace(/funcionalesde/g, 'funcionales de')
    .replace(/elmode lamiento/g, 'el modelamiento')
    .replace(/seleccionary/g, 'seleccionar y')
    .replace(/apropiadosen/g, 'apropiados en')
    .replace(/yaplicar/g, 'y aplicar')
    .replace(/capacidadde/g, 'capacidad de')
    .replace(/ofreceráuna/g, 'ofrecerá una')
    .replace(/ysocial/g, 'y social')
    .replace(/ámbitode/g, 'ámbito de')
    .replace(/Enparticular/g, 'En particular')
    .replace(/acomplejidad/g, 'a complejidad')
    .replace(/establecela/g, 'establece la')
    .replace(/seencuentran/g, 'se encuentran')
    .replace(/usanen/g, 'usan en')
    .replace(/esun/g, 'es un')
    .replace(/definede/g, 'define de')
    .replace(/elmecanismo/g, 'el mecanismo')
    .replace(/entendiblepor/g, 'entendible por')
    .replace(/esprecisamente/g, 'es precisamente')
    .replace(/quese/g, 'que se')
    .replace(/unarama/g, 'una rama')
    .replace(/loscomputadores/g, 'los computadores')
    .replace(/habilitadopor/g, 'habilitado por')
    .replace(/enespecial/g, 'en especial')
    .replace(/paradigmade/g, 'paradigma de')
    .replace(/incorporarlosa/g, 'incorporarlos a')
    .replace(/laoperación/g, 'la operación')
    .replace(/Aplicacióny/g, 'Aplicación y')
    .replace(/yllevan/g, 'y llevan')
    .replace(/delsistema/g, 'del sistema')
    .replace(/cabosesiones/g, 'cabo sesiones')
    .replace(/laaplicación/g, 'la aplicación')
    .replace(/conla/g, 'con la')
    .replace(/gestiónde/g, 'gestión de')
    .replace(/sinlas/g, 'sin las')
    .replace(/elalcance/g, 'el alcance')
    .replace(/hanalcanzado/g, 'han alcanzado')
    .replace(/gestionaradecuadamente/g, 'gestionar adecuadamente')
    .replace(/softwarede/g, 'software de')
    .replace(/estructurabásica/g, 'estructura básica')
    .replace(/lafutura/g, 'la futura')
    .replace(/laevolución/g, 'la evolución')
    .replace(/esuna/g, 'es una')
    .replace(/esimportante/g, 'es importante')
    .replace(/losparadigmas/g, 'los paradigmas')
    .replace(/yadaptarse/g, 'y adaptarse')
    .replace(/elestudiante/g, 'el estudiante')
    .replace(/lepermitirán/g, 'le permitirán')
    .replace(/gráficasde/g, 'gráficas de')
    .replace(/lenguajede/g, 'lenguaje de')
    .replace(/asignaturaque/g, 'asignatura que')
    .replace(/laque/g, 'la que')
    .replace(/uncientífico/g, 'un científico')
    .replace(/participantesen/g, 'participantes en')
    .replace(/decontrol/g, 'de control')
    .replace(/lamecánica/g, 'la mecánica')
    .replace(/laresolución/g, 'la resolución')
    .replace(/mode lar/g, 'modelar')
    .replace(/mode la/g, 'modela')
    .replace(/ycomposición/g, 'y composición')
    .replace(/diseñarformulando/g, 'diseñar formulando')
    .replace(/larealidad/g, 'la realidad')
    .replace(/clasesabstractas/g, 'clases abstractas')
    .replace(/lascolecciones/g, 'las colecciones')
    .replace(/unprograma/g, 'un programa')
    .replace(/interrumpenel/g, 'interrumpen el')
    .replace(/trescapas/g, 'tres capas')
    .replace(/\(GUI\)/g, ' (GUI)')
    .replace(/lasbases/g, 'las bases')
    .replace(/ynormalización/g, 'y normalización')
    .replace(/infra estructuras/g, 'infraestructuras')
    .replace(/estudio s/g, 'estudios')
    .replace(/otro s\./g, 'otros. ')
    .replace(/ma temática/g, 'matemática')
    .replace(/computacional mente/g, 'computacionalmente')
    .replace(/herramienta s/g, 'herramientas')
    .replace(/\/ servidor/g, '/servidor')
    .replace(/está ndares/g, 'estándares')
    .replace(/está n/g, 'están')
    .replace(/natural es/g, 'naturales')
    .replace(/natural ezaes/g, 'naturaleza es')
    .replace(/delPC/g, 'del PC')
    .replace(/yvalidar/g, 'y validar')
    .replace(/explicarmatemática mente/g, 'explicar matemáticamente')
    .replace(/devisión/g, 'de visión')
    .replace(/Trabajar en equipo Participar/g, 'Trabajar en equipo: participar')
    .replace(/proyectode/g, 'proyecto de')
    .replace(/,/g, ', ')
    .replace(/ ,/g, ',')
    .replace(/\./g, '. ')
    .replace(/ \./g, '.')
    .replace(/ ”/g, '”')
    .replace(/ \)/g, ')')
    .replace(/\. \. \./g, '...')
    .replace(/  +/g, ' ')
    .replace(/matemáticas computacional es/g, 'matemáticas computacionales')
    .replace(/computacional esrazonables/g, 'computacionales razonables')
    .replace(/aspectos computacional es de/g, 'aspectos computacionales de')
    .replace(/computacionalmente\(/g, 'computacionalmente (')
    .trim()
}

const writeFile = (
  data    : string,
  filename: string
): Promise<string> => new Promise((resolve, reject) => {
  fs.writeFile(filename, data, (error: unknown): void => {
    if (error) reject(error)
    resolve('Saved successfully')
  })
})

export { cleanGeneralInfo, writeFile }
